title: Ding Chenhao's Homepage
page-top-title: Ding Chenhao
top-section-bg-text: Be what you wanna be
home-subtitle: Ding Chenhao|(丁晨浩)
copyright-text: '&copy; Ding Chenhao 2023-2025. All Rights Reserved.'
